"use strict";
define(['model'],function($model){
	return new $model(
		{
			'meta':{
				'limit': 100,
				'title': 'Subjects'
			},
			'data':[
				{
					'id':'T1001',
					'section_id':1,
					'program_id':'BSIT',
					'subject_id':1,
					'sy':2019,
					'sem':1,
					'details':[
						{
							'id':1,
							'start_time':'06:00',
							'end_time':'09:00',
							'day':'M',
							'room':'COMLAB1'
						},
						{
							'id':2,
							'start_time':'06:00',
							'end_time':'09:00',
							'day':'W',
							'room':'COMLAB1'
						},
					]
				},
				{
					'id':2,
					'section_id':1,
					'program_id':'BSIT',
					'schedule_code':'T1002',
					'subject_id':2,
					'sy':2019,
					'sem':1
					'details':[
						{
							'id':3,
							'start_time':'09:00',
							'end_time':'12:00',
							'day':'M',
							'room':'LECROM1'
						},
						{
							'id':4,
							'start_time':'09:00',
							'end_time':'12:00',
							'day':'W',
							'room':'LECROM1'
						}
					]
				},
				{
					'id':3,
					'section_id':2,
					'program_id':'BSIT',
					'schedule_code':'T1001',
					'subject_id':1,
					'sy':2019,
					'sem':1
				},
				{
					'id':4,
					'section_id':2,
					'program_id':'BSIT',
					'schedule_code':'T1002',
					'subject_id':2,
					'sy':2019,
					'sem':1
				},
				{
					'id':5,
					'section_id':2,
					'program_id':'BSCS',
					'schedule_code':'T1001',
					'subject_id':2,
					'sy':2019,
					'sem':1
				},
				{
					'id':6,
					'section_id':1,
					'program_id':'BSIT',
					'schedule_code':'T1001',
					'subject_id':3,
					'sy':2019,
					'sem':1
					'details':[
						{
							'id':5,
							'start_time':'09:00',
							'end_time':'12:00',
							'day':'T',
							'room':'LECROM2'
						},
						{
							'id':6,
							'start_time':'09:00',
							'end_time':'12:00',
							'day':'TH',
							'room':'LECROM2'
						},
					]
				},
				{
					'id':7,
					'section_id':1,
					'program_id':'BSIT',
					'schedule_code':'T1001',
					'subject_id':4,
					'sy':2019,
					'sem':1
					'details':[
						{
							'id':7,
							'start_time':'01:00',
							'end_time':'03:00',
							'day':'T',
							'room':'LECROM2'
						},
						{
							'id':8,
							'start_time':'01:00',
							'end_time':'03:00',
							'day':'TH',
							'room':'LECROM2'
						}
					]
				},
				{
					'id':8,
					'section_id':1,
					'program_id':'BSIT',
					'schedule_code':'T1001',
					'subject_id':6,
					'sy':2019,
					'sem':1
					'details':[
						{
							'id':9,
							'start_time':'03:00',
							'end_time':'05:00',
							'day':'M',
							'room':'LECROM3'
						},
						{
							'id':10,
							'start_time':'03:00',
							'end_time':'05:00',
							'day':'W',
							'room_id':'LECROM3'
						}
					]
				},
				
				
			]
		}
	)

});