"use strict";
define(['model'],function($model){
	return new $model(
		'meta':{
			'limit':100,
			'title':'College Curriculum Details'
		},
		'data':[
			{
				'id':1,
				'curriculum_id':'IT2019',
				'subject_id':1,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'Y',
				'co_req':'N'
			},
			{
				'id':2,
				'curriculum_id':'IT2019',
				'subject_id':2,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'Y',
				'co_req':'N'
			},
			{
				'id':3,
				'curriculum_id':'IT2019',
				'subject_id':3,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'N',
				'co_req':'N'
			},
			{
				'id':4,
				'curriculum_id':'IT2019',
				'subject_id':4,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'Y',
				'co_req':'N'
			},
			{
				'id':5,
				'curriculum_id':'IT2019',
				'subject_id':6,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'N',
				'co_req':'N'
			},
			{
				'id':6,
				'curriculum_id':'CS2019',
				'subject_id':1,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'Y',
				'co_req':'N'
			},
			{
				'id':7,
				'curriculum_id':'CS2019',
				'subject_id':2,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'Y',
				'co_req':'N'
			},
			{
				'id':8,
				'curriculum_id':'CS2019',
				'subject_id':3,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'N',
				'co_req':'N'
			},
			{
				'id':9,
				'curriculum_id':'CS2019',
				'subject_id':4,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'Y',
				'co_req':'N'
			},
			{
				'id':10,
				'curriculum_id':'CS2019',
				'subject_id':6,
				'year_level_id':'T1',
				'sem':1,
				'pre_req':'N',
				'co_req':'N'
			},
		
		]
	)

});